name: Build(CI) and Inject Version

on:
  push:
    branches: [main, feature/github_actions]  # 修复分支名中的空格
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}  # 修复空格
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # 修复空格

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 修复空格

      - name: Set up CMake
        uses: threeal/cmake-action@v2

      # 计算 N：优先从最近 tag（形如 v1.0.N）解析；若无 tag 则用 1
      - name: Derive RELEASE_N
        id: version
        shell: bash
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.1")
          N=$(echo "$TAG" | awk -F. '{print $3}' | sed "s/[^0-9]//g")
          if [ -z "$N" ]; then N=1; fi
          echo "RELEASE_N=$N" >> $GITHUB_ENV
          echo "Using RELEASE_N=$N"

      - name: Configure & Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Run binary
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            ./build/Release/HelloWorld.exe
          else
            ./build/HelloWorld
          fi

      - name: Upload artifact(optional)
        uses: actions/upload-artifact@v4
        with:
          name: HelloWorld-${{ matrix.os }}
          path: |
            build/HelloWorld
            build/Release/HelloWorld.exe
